backend:
  name: github
  repo: dcorn068/mdx-28

media_folder: "public/images"
public_folder: "images"

collections:
  - name: deck
    label: Deck (markdown)
    extension: mdx
    format: frontmatter
    files:
      - file: deck.mdx
        name: deck
        label: Deck (markdown)
        fields:
          - name: body
            label: "Deck"
            widget: markdown
            required: true
